export default [{
  key: 'service',
  title: 'Services',
  choices: [{
    icon: 'one-page',
    key: 'onePage',
    title: 'Individuelle One-Page',
    subtitle: 'Individuelles On-Page Design inkl. Responsive Development',
    flexPrice: false,
    price: 8000,
  }, {
    icon: 'wordpress',
    key: 'wordpress',
    title: 'Wordpress Website',
    subtitle: 'Individuelle WordPress Website mit 6 Unterseiten',
    flexPrice: false,
    price: 25000,
  }, {
    icon: 'website-review',
    key: 'websiteReview',
    title: 'Website Review',
    subtitle: 'UX Review mit bis zu 10 UX Fallen inkl. Vorschlägen zur Verbesserung',
    flexPrice: false,
    price: 5000,
  }, {
    icon: 'app-concept',
    key: 'appConcept',
    title: 'App Konzept',
    subtitle: '10 Wireframes, 1 Design Look & Feel, aufbereitet als Präsentations- und Ausschreibungs&shy;unterlage',
    flexPrice: true,
    price: 20000,
  }, {
    icon: 'branding',
    key: 'branding',
    title: 'Markendesign',
    subtitle: 'Naming, Marken&shy;recherche, Logo, Brand Guidelines, Exporte',
    flexPrice: true,
    price: 25000,
  }, {
    icon: 'prototype',
    key: 'prototype',
    title: 'User-Test Prototyp',
    subtitle: 'Vorstands&shy;fähiger programmierter Test-Prototyp mit Daten auf bis zu 10 Views',
    flexPrice: true,
    price: 50000,
  }, {
    icon: 'web-app',
    key: 'webApp',
    title: 'Indivduelle Web App',
    subtitle: 'Basierend auf React.js (optional mit API-Anbindung)',
    flexPrice: true,
    price: 80000,
  }, {
    icon: 'mobile-app',
    key: 'mobileApp',
    title: 'Individuelle Mobile App',
    subtitle: 'React-Native (< 50% Ersparnis durch Cross-Platform-Ansatz)',
    flexPrice: true,
    price: 80000,
  }],
}, {
  key: 'workshop',
  title: 'Workshops',
  choices: [{
    icon: 'sketch',
    title: 'Einführung in Sketch',
    subtitle: 'Einführung in die Grafiksoftware Sketch',
    flexPrice: false,
    price: 8000,
  }, {
    icon: 'branding',
    title: 'Informationsdesign',
    subtitle: 'Gemeinsame Konzipierung für Ihr Finanzprodukt',
    flexPrice: false,
    price: 25000,
  }, {
    icon: 'branding',
    title: 'Konzeptionsworkshop',
    subtitle: 'Workshop über die Konzipierung eines Produkts',
    flexPrice: false,
    price: 5000,
  }, {
    icon: 'react',
    title: 'React-Native Entwicklung',
    subtitle: 'Wie durch React-Native Zeit und Geld gespart wird',
    flexPrice: true,
    price: 20000,
  }, {
    icon: 'redux',
    title: 'Skalierbare Apps mit Redux',
    subtitle: 'Mit Redux.js horizontal und vertikal einfach skalieren',
    flexPrice: true,
    price: 20000,
  }, {
    icon: 'vagrant',
    title: 'Effiziente Entwicklungs-Umgebung',
    subtitle: 'Wie Vagrant einem Entwickler helfen kann',
    flexPrice: true,
    price: 20000,
  }, {
    icon: 'react',
    title: 'Das perfekte CMS',
    subtitle: 'Welches CMS sollen Sie für Ihr nächste Webseite benutzen?',
    flexPrice: true,
    price: 20000,
  }, {
    icon: 'branding',
    title: 'Scrum einfach gemacht',
    subtitle: 'Einfache Erklärungen und Vorgehensweisen mit Scrum',
    flexPrice: true,
    price: 20000,
  }],
}];
